### ISSUE TITLE
Docker container is always restarting after new setup via git clone

### ISSUE THREAD

**Issue by KraxelHuber** [fhem/fhem-docker#21]
I am trying to integrate this container into my git version control as described in the README. At first, everything is going well, that is, once I set up a `docker-compose.yml` in my /docker/home folder on a Raspberry Pi 3, I can successfully create the container. I am using the following `docker-compose.yml`:

```
version: '2.3'

networks:
  net:
    driver: bridge
    # enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/24
          gateway: 172.27.0.1
        # - subnet: fd00:0:0:0:27::/80
        #   gateway: fd00:0:0:0:27::1

services:

  fhem:
    image: fhem/fhem:latest
    container_name: fhem_slave
    restart: always
    networks:
      - net
    ports:
      - "8083:8083"
    volumes:
      - "./fhem/:/opt/fhem/"
    devices:
      - "dev/ttyACM0:/dev/ttyACM0"
      - "dev/ttyACM1:/dev/ttyACM1"
      - "dev/ttyAMA0:/dev/ttyAMA0"
    environment:
      FHEM_UID: 6061
      FHEM_GID: 6061
      TIMEOUT: 10
      RESTART: 1
      TELNETPORT: 7072
      TZ: Europe/Berlin
```

After first start of the container, FHEM is up and running. I then did some changes within the frontend of FHEM, did an `update all` and then commited those changes to my online repo at bitbucket. I wanted to try if this is working as a suitable backup solution. To test it, I stopped and removed the container and completely deleted the home folder using `sudo rm -r home`. Then, I cloned my online repo back into the home folder. All files looked exactly the same as before I deleted the home folder. However, when trying to build the container and start it via `docker-compose up -d` the container is not starting properly anymore. Using `docker ps`, I can see that it always tries to start the container for some seconds. It looks like the container is in a restarting loop.

![grafik](https://user-images.githubusercontent.com/29901736/57733401-ba5c4e80-769f-11e9-9177-0ca118fb00ab.png)

I'm wondering what I am supposed to do in order to check what causes these restart issues?
