### ISSUE TITLE
Folder copied to ./www/images isn't recognized

### ISSUE THREAD

**Issue by binford6000** [fhem/fhem-docker#323]
**Describe the bug**
I want to add a folder (of icons as .png) under ./www/inages.

**Expected behavior**
Icons in the newly added folder are recognized bei FHEMWEB like in traditional VM deployment.

**Current behaviour:**
Icons arent recognized due to the fact that the folder won't show up inside the container.

**To Reproduce**

**What I did on "VM-FHEM":**

- copied emoji16 folder to ./www/images
- `chown -R fhem:dialout ./www/images/emoji16`
- In FHEM `set WEB reload icons`
- `get WEB icon emoji_u1f9ff` returns `./www/images/emoji16/emoji_u1f9ff.png`

**What I did on "docker-FHEM":**

- copied emoji16 folder to ./volumes/fhem_fhem_data/_data/opt/fhem/www/images
- shutdown+restart to chown files/folders:

INFO: Stopping container. Bye!
INFO: Preparing user environment
INFO: Creating group 'fhem' with GID 6061
INFO: Enforcing GID for group 'bluetooth' to 6001
INFO: Creating user 'fhem' with UID 6061
INFO: Creating log directory /opt/fhem/log
INFO: Creating PID directory /opt/fhem/log
INFO: Enforcing user and group ownership for /opt/fhem to fhem:fhem
INFO: Enforcing file and directory permissions for /opt/fhem 
INFO: Correcting group ownership for /dev/tty* 
INFO: Found GPIO: Correcting group permissions in /dev and /sys to 'gpio' with GID 6002 
INFO: Found I2C: Correcting group permissions in /dev to 'i2c' with GID 6003
 
- `get WEB icon emoji_u1f9ff` returns `no such icon` 

You can see that the added folder is missing inside the container but shows up in the volume
with correct uid/gig and permissions:

- ls on fhem container:

root@00027b04b36e:/opt/fhem/www/images# ls -la
total 484
drwxr-x--- 11 fhem fhem   4096 Jan 11 16:00 .
drwxr-x--- 17 fhem fhem   4096 Jan 19 10:00 ..
drwxr-x---  2 fhem fhem   4096 Okt 24  2018 background
-rw-r-----  1 fhem fhem 104086 Mär  5  2024 blank.png
drwxr-x---  5 fhem fhem  12288 Mär 31  2024 default
drwxr-x---  3 fhem fhem  28672 Mai 20 09:11 fhemSVG
-rw-r-----  1 fhem fhem    140 Sep 14  2022 FritzBox.m3u
-rw-r-----  1 fhem fhem   4605 Sep 11  2019 gastwlan.png
drwxr-x---  2 fhem fhem 266240 Nov 22 08:16 mdt
drwxr-x---  2 fhem fhem  20480 Jan 11 16:00 moonphase
drwxr-x---  2 fhem fhem  24576 Feb 15 07:17 openautomation
drwxr-x---  2 fhem fhem   4096 Nov 30  2022 snapshots
drwxr-x---  2 fhem fhem   4096 Apr  9  2021 sscam
drwxr-x---  3 fhem fhem   4096 Dez 11  2017 weather

- ls on docker host:

root@docker:/var/lib/docker/volumes/fhem_fhem_data/_data/www/images# ls -la
insgesamt 744
drwxr-x--- 12 6061 6061   4096 Mai 20 14:50 .
drwxr-x--- 17 6061 6061   4096 Jan 19 11:34 ..
drwxr-x---  2 6061 6061   4096 Okt 24  2018 background
-rw-r-----  1 6061 6061 104086 Mär  5  2024 blank.png
drwxr-x---  5 6061 6061  12288 Mai 20 14:50 default
drwxr-x---  2 6061 6061 233472 Mai 20 08:50 emoji16
drwxr-x---  3 6061 6061  24576 Apr 12 21:40 fhemSVG
-rw-r-----  1 6061 6061    140 Sep 14  2022 FritzBox.m3u
-rw-r-----  1 6061 6061   4605 Sep 11  2019 gastwlan.png
drwxr-x---  2 6061 6061 294912 Nov 22 09:16 mdt
drwxr-x---  2 6061 6061  20480 Jan 11 17:32 moonphase
drwxr-x---  2 6061 6061  24576 Feb 15 08:21 openautomation
drwxr-x---  2 6061 6061   4096 Nov 30  2022 snapshots
drwxr-x---  2 6061 6061   4096 Apr  9  2021 sscam
drwxr-x---  3 6061 6061   4096 Dez 11  2017 weather

uid and gid are pretty the same like all the other subfolders but inside the container
it doesn't show up.

Even a recreation of the stack via docker compose results in not showing the folder.

Happy to help with anything!

**Comment by sidey79** [comment]
Can you please share your docker compose file.
I think there may bei an config error within your volume mounts.

**Comment by sidey79** [comment]
I tested this and there seems no problem using additonal images inside the container

```
root@1eb0c1f4de59:/opt/fhem# ls www/images/emoji16/emoji_u1f9ff.png  -l
-rw-r----- 1 fhem fhem 0 May 20 22:18 www/images/emoji16/emoji_u1f9ff.png
```

**Comment by binford6000** [comment]
```
# complete fhem stack with fhem and sonons2mqtt + polly
networks:
  net:
    driver: bridge
    # enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/28
          gateway: 172.27.0.1
        # - subnet: fd00:0:0:0:27::/80
        #   gateway: fd00:0:0:0:27::1

services:
  # fhem with latest image
  fhem:
    build:
      context: .
      dockerfile_inline: |
        FROM ghcr.io/fhem/fhem-docker:5-bookworm
        RUN <<EOF
          cpm install --show-build-log-on-failure --configure-timeout=360 --workers=$(nproc) --local-lib-contained /usr/src/app/3rdparty/ Crypt::Cipher::AES Crypt::Rijndael_PP Math::Round
          LC_ALL=C DEBIAN_FRONTEND=noninteractive apt-get update
          LC_ALL=C DEBIAN_FRONTEND=noninteractive apt-get install -qqy --no-install-recommends nano htop mc libjson-perl libdigest-md5-perl libcrypt-cbc-perl libcrypt-ecb-perl
          LC_ALL=C apt-get autoremove -qqy && LC_ALL=C apt-get clean
          LC_ALL=C curl -L https://www.npmjs.com/install.sh | sudo bash
          LC_ALL=C npm install -g npm@10
          npm install -g --unsafe-perm --production alexa-fhem
          npm cache clean --force
          cat <<EOF >> /etc/ssh/ssh_config
        Host fhem-va.fhem.de
          HostkeyAlgorithms +ssh-rsa
          PubkeyAcceptedAlgorithms +ssh-rsa
        EOF
    pull_policy: build
    restart: always
    container_name: fhem
    networks:
      - net
    ports:
      - "8083:8083"
      - "8885:8885"
      - "7072:7072"
      - "8002:8002" # alexa-fhem custom skill
      #- "1883:1883" # MQTT2 Server if needed
    volumes:
      - fhem_data:/opt/fhem
    environment:
      FHEM_UID: 6061
      FHEM_GID: 6061
      RESTART: 1
      BLUETOOTH_GID: 6001
      CONFIGTYPE: fhem.cfg
      GPIO_GID: 6002
      I2C_GID: 6003
      LANG: de_DE.UTF-8
      LANGUAGE: de_DE:de
      LC_ADDRESS: de_DE.UTF-8
      LC_MEASUREMENT: de_DE.UTF-8
      LC_MESSAGES: de_DE.UTF-8
      LC_MONETARY: de_DE.UTF-8
      LC_NAME: de_DE.UTF-8
      LC_NUMERIC: de_DE.UTF-8
      LC_PAPER: de_DE.UTF-8
      LC_TELEPHONE: de_DE.UTF-8
      LC_TIME: de_DE.UTF-8
      LOGFILE: ./log/fhem-%Y-%m-%d.log
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      TELNETPORT: 7072
      TERM: xterm
      TIMEOUT: 10
      TZ: Europe/Berlin
      UMASK: 0037

  # sonos2mqtt + polly tts
  sonos:
    container_name: sonos2mqtt
    image: svrooij/sonos2mqtt:3.2.0-beta.19
    restart: unless-stopped
    networks:
      - net
    ports:
      - "6329:6329"
    environment:
      SONOS2MQTT_DEVICE: 10.3.3.142
      SONOS2MQTT_DISCOVERY: true
      SONOS2MQTT_MQTT: "mqtt://user:pass@10.3.3.4:1883"
      SONOS2MQTT_CLIENTID: sonos2mqtt
      SONOS_LISTENER_HOST: ${HOST_IP} 
      SONOS_TTS_ENDPOINT: http://${HOST_IP}:5601/api/generate
      SONOS2MQTT_TTSLANG: de-DE
      TZ: Europe/Berlin
      # New AudioClip notifications (latest beta version needed):
      SONOS2MQTT_EXPERIMENTAL: true

  polly:
    container_name: sonos-tts-polly
    image: ghcr.io/svrooij/node-sonos-tts-polly:1.0.10-beta.2
    networks:
      - net
    restart: unless-stopped
    ports:
      - "5601:5601"
    environment:
      SONOS_TTS_AMAZON_KEY: <key>
      SONOS_TTS_AMAZON_SECRET: <secret>
      SONOS_TTS_AMAZON_REGION: eu-central-1
      SONOS_TTS_CACHE_URI: http://${HOST_IP}:5601/cache/

volumes:
  fhem_data:
  #alexa-fhem_data:
```
